### ISSUE TITLE
Show an error message when user tries to sign up without giving a name

### ISSUE THREAD

**Issue by Steveo1485** [Steveo1485/pokedex#34]

**Comment by Steveo1485** [comment]
Having problems with the CSS not compiling when using Capybara/Selenium. Shows this error on Firefox during the test:
Error compiling CSS asset
Sass:SyntaxError: File to import not found or unreadable: global.

But wanted to check with you since you have more experience with SASS.

Otherwise the Javascript confirmation works. But will get the test error figured out before pull request.

**Comment by smart-alek** [comment]
That shouldn't really be a problem. Essence used .scss and we still ran Capybara/Selenium testing suites just fine. So, this is just a testing bug, then?

**Comment by Steveo1485** [comment]
Was able to get scss to compile in tests by changing the @import calls in application.css to use a require_directory ., used Essence for reference.

I also removed out before(:each) test configuration (was set to DatabaseCleaner.start) because it was messing with the Trainer.create calls in the feature tests. I didn't get this error when using Capybara steps to sign up. Do you have a preference over which to use? (Either do sign-up through Capybara and include before(:each), or use Trainer.create and remove before(:each).

I'll make a pull request, but if you want to keep the before(:each) and use Capybara to create Trainers, let me know and I'll update the pull request.
