### ISSUE TITLE
Selenium-webdriver; forces use of Firefox?

### ISSUE THREAD

**Issue by smart-alek** [Steveo1485/pokedex#42]
Is there a way to set this up for Chrome? I had to download and install Firefox in order to get a few integration tests to work. Will research a bit later today.

**Comment by Steveo1485** [comment]
Not that I know of. I've always had to use Firefox. Let me know what you find.

**Comment by smart-alek** [comment]
Checked it out; Chrome uses its own webdriver, and I don't think it's worth our time right now to adjust so we are only using one web browser. That's Google's job. If we worked at Google, it would be our job.
