### ISSUE TITLE
Delete trainer link scope

### ISSUE THREAD

**Issue by smart-alek** [Steveo1485/pokedex#48]
The user does not currently have to click directly on the link in order to get the JavaScript confirmation. Somehow, the way we've configured the CSS has made it so that there is a rectangular strip across the screen that accepts a click for that link.

Will look into this further on my next round of refactoring.

**Comment by Steveo1485** [comment]
The #quit styling was set to display: block, which was allowing the link to take up the full line on the page. Removed the display property from the #quit styling to fix. Pull request is open for fix.
